# Generated by Django 4.0.4 on 2022-11-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudacityIssue',
            fields=[
                ('issueNumber', models.IntegerField(db_column='IssueNumber', primary_key=True, serialize=False)),
                ('issueTitle', models.TextField(default='')),
                ('issueText', models.TextField(default='')),
                ('issueLabels', models.TextField(default='')),
                ('Util', models.BooleanField()),
                ('APM', models.BooleanField()),
                ('Network', models.BooleanField()),
                ('DB', models.BooleanField()),
                ('Error_Handling', models.BooleanField(db_column='Error.Handling')),
                ('Logging', models.BooleanField()),
                ('Lang', models.BooleanField()),
                ('Data_Structure', models.BooleanField(db_column='Data.Structure')),
                ('i18n', models.BooleanField()),
                ('Setup', models.BooleanField()),
                ('Logic', models.BooleanField()),
                ('IO', models.BooleanField()),
                ('UI', models.BooleanField()),
                ('Parser', models.BooleanField()),
                ('Event_Handling', models.BooleanField(db_column='Event.Handling')),
                ('App', models.BooleanField()),
                ('GIS', models.BooleanField()),
                ('Multimedia', models.BooleanField()),
                ('CG', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JabRefIssue',
            fields=[
                ('issueNumber', models.IntegerField(db_column='IssueNumber', primary_key=True, serialize=False)),
                ('issueTitle', models.TextField(default='')),
                ('issueText', models.TextField(default='')),
                ('issueLabels', models.TextField(default='')),
                ('Util', models.BooleanField()),
                ('NLP', models.BooleanField()),
                ('APM', models.BooleanField()),
                ('Network', models.BooleanField()),
                ('DB', models.BooleanField()),
                ('Interpreter', models.BooleanField()),
                ('Logging', models.BooleanField()),
                ('Data_Structure', models.BooleanField(db_column='Data.Structure')),
                ('i18n', models.BooleanField()),
                ('DevOps', models.BooleanField()),
                ('Logic', models.BooleanField()),
                ('Microservices', models.BooleanField()),
                ('Test', models.BooleanField()),
                ('Search', models.BooleanField()),
                ('IO', models.BooleanField()),
                ('UI', models.BooleanField()),
                ('Parser', models.BooleanField()),
                ('Security', models.BooleanField()),
                ('App', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerToysIssue',
            fields=[
                ('issueNumber', models.IntegerField(db_column='IssueNumber', primary_key=True, serialize=False)),
                ('issueTitle', models.TextField(default='')),
                ('issueText', models.TextField(default='')),
                ('issueLabels', models.TextField(default='')),
                ('APM', models.BooleanField()),
                ('Interpreter', models.BooleanField()),
                ('Logging', models.BooleanField()),
                ('Data_Structure', models.BooleanField(db_column='Data.Structure')),
                ('i18n', models.BooleanField()),
                ('Setup', models.BooleanField()),
                ('Logic', models.BooleanField()),
                ('Microservices', models.BooleanField()),
                ('Test', models.BooleanField()),
                ('Search', models.BooleanField()),
                ('UI', models.BooleanField()),
                ('Parser', models.BooleanField()),
                ('App', models.BooleanField()),
            ],
        ),
    ]
