# Generated by Django 4.1.2 on 2022-10-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JabRefIssue',
            fields=[
                ('issueNumber', models.IntegerField(db_column='IssueNumber', primary_key=True, serialize=False)),
                ('Util', models.BooleanField()),
                ('NLP', models.BooleanField()),
                ('APM', models.BooleanField()),
                ('Network', models.BooleanField()),
                ('DB', models.BooleanField()),
                ('Interpreter', models.BooleanField()),
                ('Logging', models.BooleanField()),
                ('Data_Structure', models.BooleanField(db_column='Data.Structure')),
                ('i18n', models.BooleanField()),
                ('DevOps', models.BooleanField()),
                ('Logic', models.BooleanField()),
                ('Microservices', models.BooleanField()),
                ('Test', models.BooleanField()),
                ('Search', models.BooleanField()),
                ('IO', models.BooleanField()),
                ('UI', models.BooleanField()),
                ('Parser', models.BooleanField()),
                ('Security', models.BooleanField()),
                ('App', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerToysIssue',
            fields=[
                ('issueNumber', models.IntegerField(db_column='IssueNumber', primary_key=True, serialize=False)),
                ('APM', models.BooleanField()),
                ('Interpreter', models.BooleanField()),
                ('Logging', models.BooleanField()),
                ('Data_Structure', models.BooleanField(db_column='Data.Structure')),
                ('i18n', models.BooleanField()),
                ('Setup', models.BooleanField()),
                ('Logic', models.BooleanField()),
                ('Microservices', models.BooleanField()),
                ('Test', models.BooleanField()),
                ('Search', models.BooleanField()),
                ('UI', models.BooleanField()),
                ('Parser', models.BooleanField()),
                ('App', models.BooleanField()),
            ],
        ),
    ]
