# Generated by Django 4.1.2 on 2022-11-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GiveMeLabeledIssues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabrefissue',
            name='issueText',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jabrefissue',
            name='issueTitle',
            field=models.TextField(default=''),
        ),
    ]
