# Generated by Django 4.1.2 on 2022-11-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GiveMeLabeledIssues', '0002_alter_jabrefissue_issuetext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powertoysissue',
            name='issueText',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='powertoysissue',
            name='issueTitle',
            field=models.TextField(default=''),
        ),
    ]
