# Generated by Django 4.1.2 on 2022-11-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GiveMeLabeledIssues', '0003_alter_powertoysissue_issuetext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jabrefissue',
            name='issueLabels',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='powertoysissue',
            name='issueLabels',
            field=models.TextField(default=''),
        ),
    ]
